app/src/main/java/decide/LICS.java
Initializes LICS with dummy signatures for ease of usage.
=> Initializes LICS with dummy signatures.

.gitignore, app/src/main/java/decide/InputVariables.java, app/src/main/java/decide/OutputVariables.java, app/src/main/java/decide/Parameters.java, app/src/main/java/decide/Point.java
Added four files and initialized variables.
[InputVariables.java](https://github.com/hansstammler/DECIDE/blob/3-global-parameter-model-missing/app/src/main/java/decide/InputVariables.java)
[OutputVariables.java](https://github.com/hansstammler/DECIDE/blob/3-global-parameter-model-missing/app/src/main/java/decide/OutputVariables.java)
[Parameters.java](https://github.com/hansstammler/DECIDE/blob/3-global-parameter-model-missing/app/src/main/java/decide/Parameters.java)
[Point.java](https://github.com/hansstammler/DECIDE/blob/3-global-parameter-model-missing/app/src/main/java/decide/Point.java)
=> feat: 3 global parameter model missing

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Initialized LICSTest.java and chanegd LICS.java so that each LIC is static and has Parameters object as argument.
=> 21 fix change the lic functions and initialize licstest

app/src/main/java/decide/Point.java
Point.java was 3D but in the assginment only x and y is used. Removed third dimension.
=> fix: Changed Point.java to be 2D instead of 3D #10

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Finished Issue 10 by adding code, documentation and test.
=> Finished issue #10

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Added code and documentation for LIC eleven.
Also created unit test for LIC eleven.
=> fix: added code and tests for LIC11 #18

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Added code and comment for LIC13. Quite messy right now and will have to refactor later, but it seems to work. Added unit test for LIC13.
=> fix: added code and tests for LIC13 #13

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
I interpreted LIC13 wrong the first time and I've corrected the error. Also changed the test to actually test what the task was.
=> fix: bug fixed LIC13 and updated test (#29)

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Implements LIC10 and adds an implementation.
=> Implements LIC10 and adds tests for it.

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Might need help to find out why the test fails. Should be ok to merge this one since issue #54 is created for this.
=> feat: LIC12 with tests, although the last test fails

app/src/main/java/decide/App.java, app/src/test/java/decide/AppTest.java
Initialized methods and objects needed to create DECIDE to make splitting work up easier.
=> feat: initialized code skeleton for DECIDE #59

app/src/main/java/decide/PUM.java
Adds a class that models the PU matrix. It has a getter to retreive the results at all available indexes.
=> feat: Implements PUM

app/src/main/java/decide/LICS.java
Added javadoc for LIC1, 8 and 14, please review and merge
=> doc: Added javadoc for LIC1, 8 and 14 (issue #65)

app/src/test/java/decide/LICSTest.java
=> 67 lic test one is missing pre and postconditions + refactor

.vscode/settings.json, app/src/test/java/decide/LICSTest.java
=> 69 lic test ten is missing pre and postconditions + refactor

app/src/test/java/decide/LICSTest.java
Changed naming convention to match the rest
=> fix: changed naming convention on LIC5, 11, 13 #80

app/src/test/java/decide/LICSTest.java
Added javadoc for tests for LIC3, 4 and 14 with correct preconditions and expected result
=> doc: Added javadoc for tests for LIC3, 4 and 14 (issue #72)

app/src/test/java/decide/DECIDETest.java
Adds a second positive test for the DECIDE function.
=> feat: adds a second positive test for the whole DECIDE function, see #50.

app/src/main/java/decide/LogicalConnectorMatrix.java
Added 'a' as a flag to LCM in order to make a LCM with only ANDD's (issue #96)
=> feat: Added 'a' as a flag to LCM

app/src/main/java/decide/App.java, app/src/test/java/decide/DECIDETest.java
The tests work and are ready to be merged, see #50 .
=> 50 three main test cases

app/src/main/java/decide/LICS.java, app/src/test/java/decide/LICSTest.java
Added one test that failed the original LIC4 function and then remade the LIC4 function to pass the test.
=> 99 lic4 does not return correct value
